#' Plots \emph{MMopt} objects 
#'
#' Simulated observations are plotted on the y-axis vs. time on the x.axis.  
#' Optimal sampling times are indicated as vertical lines.
#' 
#' @title Plot Pmetrics Multiple-Model Optimal Sampling Objects
#' @method plot MMopt
#' @param x The name of an \emph{MMopt} data object generated by \code{\link{MMopt}}
#' @param mm.col Color of the optimal sample time reference lines.  Default is red.
#' @param mm.lty Type of the optimal sample time reference lines.  Default is dashed.
#' @param mm.lwd Width of the optimal sample time reference lines.  Default is 2.
#' @param \dots Other parameters to pass to \code{\link{plot.PMsim}}.
#' @return Plots the simulation profiles with MMoptimal times indicated as vertical lines.
#' @author Michael Neely
#' @seealso \code{\link{plot.PMsim}}, \code{\link{plot}}, \code{\link{par}}, \code{\link{axis}}
#' @export


plot.MMopt <- function(x,mm.col="red",mm.lty=2,mm.lwd=2,...){
  #parse dots
  arglist <- list(...)
  if(length(arglist)>0){
    if(!"probs" %in% names(arglist)){arglist$probs <- NA} 
  } else {
    arglist$probs <- NA
  }
  do.call(plot.PMsim,c(list(x$simdata),arglist))
  abline(v=x$sampleTime,col=mm.col,lty=mm.lty,lwd=mm.lwd)
}
