#' Print \emph{MMopt} objects 
#'
#' Simulated observations are plotted on the y-axis vs. time on the x.axis.  
#' Optimal sampling times are indicated as vertical lines.
#' 
#' @title Print Pmetrics Multiple-Model Optimal Sampling Objects
#' @method print MMopt
#' @param x The name of an \emph{MMopt} data object generated by \code{\link{MMopt}}
#' @return Prints the optimal sampling times and Bayes Risk.
#' @author Michael Neely
#' @seealso \code{\link{MMopt}}
#' @export


print.MMopt <- function(x){

  cat("Multiple model optimal sample times\n")
  cat("-----------------------------------\n")
  for(i in 1:length(x$sampleTime)){
    cat(paste("Sample ",i,": ",x$sampleTime[i],"\n",sep=""))
  }
  cat(paste("\nBayes Risk: ",x$bayesRisk,"\n",sep=""))
  
}
