#' Generates a summary of an IT2B run
#'
#' Creates an HTML page and several files summarizing an IT2B run.  This report is generated
#' automatically at the end of a successful run.
#'
#' @title Summarize IT2B Run
#'
#' @param wd The working directory containing the IT_RFxxxx.TXT file
#' @param icen Median (default) or mean of Bayesian posterior to be used to calculate predictions.
#' @return Several files are placed in the \code{wd}
#' \item{IT2Breport.html }{An .html file containing a summary of all the results}
#' \item{poparam.csv }{A .csv file containing a summary of the population parameter values, including
#' mean, standard deviation, coefficient of variation, variance, and median}
#' \item{popcor.csv }{A .csv file containing the population parameter correlation matrix}
#' \item{popcov.csv }{A .csv file containing the population parameter covariance matrix}
#' \item{cycle.pdf }{A .pdf file containing the run cycle information (see \code{\link{plot.PMcycle}})}
#' \item{cycle.png }{A thumbnail of the run cycle information for the .html file}
#' \item{final.pdf }{A .pdf file containing the population final cycle information (see \code{\link{plot.PMfinal}})}
#' \item{final.png }{A thumbnail of the population final cycle information for the .html file}
#' \item{opx.pdf }{One or more .pdf files, where \emph{x} is the number of the output equation, each containing
#' two observed vs. predicted plots: population and individual Bayesian posterior predictions (see \code{\link{plot.PMop}})}
#' \item{opx.png }{One or more thumnails of the observed vs. predicted plots for the .html file}
#' \item{IT2Bout.Rdata }{An R data file containing the output of \code{\link{ITparse}}, \code{\link{makeFinal}},
#' \code{\link{makeCycle}}, \code{\link{makeOP}}, \code{\link{makeCov}}, and 
#' the data file for the run read by \code{\link{PMreadMatrix}}..  This file can be loaded using \code{\link{ITload}}.}
#' @author Michael Neely

ITreport <- function(wd,icen="median"){
  setwd(wd)
  if (file.exists("IT_RF0001.TXT")){
    ITdata <- ITparse()
    cat("\n\n")
    flush.console()
    CSSfile <- paste(.libPaths(),"/Pmetrics/report/Pmetrics.css",sep="")
    if(length(grep("R2HTML",installed.packages()[,1]))==0){
      install.packages("R2HTML",dependencies=T)
    }
    require(R2HTML)
    target <- HTMLInitFile(wd,"IT2Breport",CSSFile=CSSfile,Title="IT2B output")
    #header
    dtstamp <- format(Sys.time(),"%d %b %Y at %H:%M")
    HTML("<h4>Laboratory of Applied Pharmacokinetics&nbsp&nbsp&#8226&nbsp&nbsp 2250 Alcazar St., CSC 134B Los Angeles, CA 90033&nbsp&nbsp&#8226&nbsp&nbsp(323) 442-1300
        &nbsp&nbsp&#8226&nbsp&nbsp<a href='http://www.lapk.org' target='_blank'>www.lapk.org</a><br>")
    HTML(paste("<h1>Report generated by Pmetrics package for R on",dtstamp,"</h1>"))
    HTML("<h2 id='Contents'>Table of Contents</h2>")
    HTMLli("<a href='#Summary'>Summary</a>")
    HTMLli("<a href='#Cycle'>Cycle information</a>")
    HTMLli("<a href='#Marginals'>Marginal population parameter distributions</a>")
    HTMLli("<a href='#Param'>Population parameter estimate summary statistics</a>")
    HTMLli("<a href='#Cov'>Covariance matrix for population parameter estimates</a>")
    HTMLli("<a href='#Cor'>Correlation matrix for population parameter estimates</a>")
    HTMLli("<a href='#OP'>Observed vs. predicted plots</a>")
    HTMLbr(x=3)
    
    #summary
    if(ITdata$nofix==0){parfix <- "There were no fixed parameters."
    } else {parfix <- paste("Fixed parameters:",paste(ITdata$parfix,collapse=", "))}
    if(is.null(ITdata$converge)){
      converge <- ITdata$ilog[ITdata$icyctot]-ITdata$ilog[ITdata$icyctot-1]
      if(converge > 0.001) {coninterp <- "(The run converged.)"} else {coninterp <- "(The run did not converge before the last cycle.)"}
    } else {
      coninterp <- switch(1+ITdata$converge,"(The run did not converge before the last cycle.)","(The run converged.)","","(<span style='color:red'>The run ended with a Hessian Error.</span>)")
    }
    
    
    
    HTML("<h2 id='Summary'>Summary
         &nbsp<a href='#Contents'><span>Back to Contents</span></a>
         &nbsp<a href='#Cycle'><span>Next Section</span></a></h2>")
    if(length(ITdata$fixedpos)>0) {
      fixedvar <- paste("(",paste(ITdata$par[ITdata$fixedpos],collapse=", ")," fixed to be positive)",sep="")
    } else {fixedvar <- ""}
    HTML(paste("Output file: <a href=",file.path(wd),"/IT_RF0001.TXT target=_blank>",file.path(wd),"/IT_RF0001.TXT</a><br>",
               "Random parameters: ",paste(paste(ITdata$par,collapse=", "),fixedvar,sep=" "),"<br>",
               parfix,"<br>",
               "Number of analyzed subjects: ",ITdata$nsub,"<br>",
               "Number of output equations: ",ITdata$numeqt,"<br>",
               "Number of cycles: ",ITdata$icyctot,"  ",coninterp,"<br",
               "Additional covariates: ",paste(ITdata$covnames,collapse=", "),sep=""))
    if (ITdata$negflag){ HTML("WARNING: There were negative pop/post predictions.")}
    HTMLbr(x=2)
    
    #icycle plot
    if(ITdata$icyctot > 0){
      cycle <- suppressWarnings(tryCatch(makeCycle(ITdata),error = function(e) {e <- NULL;cat("\nWARNING: error in extraction of cycle information; 'PMcycle' object not saved.\n\n")}))
      if(!all(is.null(cycle))){
        pdf(file="cycle.pdf",width=12,height=10); plot(cycle,cex.lab=1.4,font=2,cex.axis=1.2); dev.off()
        png(filename="cycle.png",width=1200,height=1000); plot(cycle,cex.lab=1.4,font=2,cex.axis=1.2); dev.off()
        HTML("<h2>Cycle information
            &nbsp<a id='Cycle' href='cycle.pdf'><span>Open file</span></a>
             &nbsp<a href='#Contents'><span>Back to Contents</span></a>
             &nbsp<a href='#Marginals'><span>Next Section</span></a></h2>")
        HTML("<img border='0' src='cycle.png' alt='Cycle Information' />")
      } else {
        HTML("<h2>Cycle information
            &nbsp<a id='Cycle'></a>
             &nbsp<a href='#Contents'><span>Back to Contents</span></a>
             &nbsp<a href='#Marginals'><span>Next Section</span></a></h2>")
        HTML("No cycles in this run.")
      }
    }
    #marginals
    final <- suppressWarnings(tryCatch(makeFinal(ITdata),error = function(e) {e <- NULL;cat("\nWARNING: error in extraction of final cycle parameter values; 'PMfinal' object not saved.\n\n")}))
    if(!all(is.null(final))){
      report.table <- data.frame(mean=final$popMean,sd=final$popSD,CV=final$popCV,var=final$popVar,
                                 median=final$popMedian)
      pdf(file="final.pdf",width=12,height=4*ceiling(ITdata$nvar/3)); plot(final,cex.lab=2.0,font=2,cex.axis=1.5); dev.off()
      png(filename="final.png",width=1200,height=400*ceiling(ITdata$nvar/3)); plot(final,cex.lab=2.0,font=2,cex.axis=1.5); dev.off()
      HTML("<h2>Marginal population parameter distributions
            &nbsp<a id='Marginals' href='final.pdf'><span>Open file</span></a>
           &nbsp<a href='#Contents'><span>Back to Contents</span></a>
           &nbsp<a href='#Param'><span>Next Section</span></a></h2>")
      HTML("<img border='0' src='final.png' alt='Marginal Densities' />")
      #popparam
      HTML("<h2>Population parameter estimate summary statistics
            &nbsp<a id='Param' href='popparam.csv'><span>Open file</span></a>
           &nbsp<a href='#Contents'><span>Back to Contents</span></a>
           &nbsp<a href='#Cov'><span>Next Section</span></a></h2>")
      HTML(report.table,align="left")
      #covariance matrix
      HTML("<h2>Covariance matrix for population parameter estimates
            &nbsp<a id='Cov' href='popcov.csv'><span>Open file</span></a>
           &nbsp<a href='#Contents'><span>Back to Contents</span></a>
           &nbsp<a href='#Cor'><span>Next Section</span></a></h2>")
      HTML(final$popCov,align="left")
      #correlation matrix
      HTML("<h2>Correlation matrix for population parameter estimates
            &nbsp<a id='Cor' href='popcor.csv'><span>Open file</span></a>
           &nbsp<a href='#Contents'><span>Back to Contents</span></a>
           &nbsp<a href='#OP'><span>Next Section</span></a></h2>")
      HTML(final$popCor,align="left")
    }
    #OP
    HTML("<h2 id='OP'>Observed vs. predicted plots
            &nbsp<a href='#Contents'><span>Back to Contents</span></a></h2>")
    op <- suppressWarnings(tryCatch(makeOP(ITdata,icen=icen),error = function(e) {e <- NULL;cat("\nWARNING: error in extraction of observed vs. population predicted data; 'PMop' object not saved.\n\n")}))
    for (i in 2*(1:ITdata$numeqt)){
      if(!all(is.null(op))){  
        OPpng <-paste("op",i/2,".png",sep="")
        OPpdf <-paste("op",i/2,".pdf",sep="")
        HTML(paste("<h3>Output",i/2,"&nbsp<a href='",OPpdf,"'><span>Open file</span></a></h3>"))
        png(filename=OPpng,width=1200,height=600)
        par(mfrow=c(1,2))
        plot(op[[i-1]],ylab="Population Predicted",x.stat=0.4,cex.stat=1.2,font=2)
        plot(op[[i]],ylab="Individual Predicted",x.stat=0.4,cex.stat=1.2,font=2)
        par(mfrow=c(1,1))
        dev.off()
        pdf(file=OPpdf,width=12,height=6)
        par(mfrow=c(1,2))
        plot(op[[i-1]],ylab="Population Predicted",x.stat=0.4,cex.stat=1.0,font=2)
        plot(op[[i]],ylab="Individual Posterior Predicted",x.stat=0.4,cex.stat=1.0,font=2)
        par(mfrow=c(1,1))
        dev.off()
        HTML(paste("<img border='0' src='",OPpng,"' alt='OPplot' />",sep=""))
      }
    }
    
    HTMLEndFile()
    
    cov <- suppressWarnings(tryCatch(makeCov(ITdata),error = function(e) {e <- NULL;cat("\nWARNING: error in extraction of covariate-parameter data; 'PMcov' object not saved.\n\n")}))
    if(!all(is.null(final))){
      write.csv(report.table,"popparam.csv",row.names=T)
      write.csv(final$popCov,"popcov.csv",row.names=T)
      write.csv(final$popCor,"popcor.csv",row.names=T)
    }
    
    if(ITdata$mdata != "NA") {mdata <- PMreadMatrix(paste("../inputs/",ITdata$mdata,sep=""),quiet=T)} else {mdata <- NA}
    
    cat(paste("\n\n\nSaving R data objects to ",wd,"......\n\n",sep=""))
    cat("\nUse ITload() to load them.\n")
    cat("\nThe following objects have been saved:\n")
    cat("\nITdata: All output from IT2B\n")
    if(!all(is.null(final))) cat("final: Final cycle population support points and parameter summary statistics\n")
    if(!all(is.null(cycle))) cat("cycle: Cycle log-likelihood, AIC, BIC, Gamma/lambda, and normalized parameter means, medians and SDs\n")
    if(!all(is.null(op))) cat("op: Observed vs. population and posterior predicted plots for each output equation\n")
    if(!all(is.null(cov))) cat("cov: Covariates and Bayesian posterior parameter estimates for each individual\n")
    if(length(mdata)>1) cat("mdata: The data file used for the run\n")
    IT2Bout <- list(ITdata=ITdata,final=final,cycle=cycle,op=op,cov=cov,mdata=mdata)
    save(IT2Bout,file="IT2Bout.Rdata")
    
  } else {cat("IT_RF0001.TXT is not in the current directory.\n")}
}
