#' Generates a summary of an NPAG run
#'
#' Creates an HTML page and several files summarizing an NPAG run.  This report is generated
#' automatically at the end of a successful run.
#'
#' @title Summarize NPAG Run
#'
#' @param wd The working directory containing the NP_RFxxxx.TXT file
#' @param icen Median (default), mean or mode of Bayesian posterior to be used to calculate predictions.
#' @return Several files are placed in the \code{wd}
#' \item{NPAGreport.html }{An .html file containing a summary of all the results}
#' \item{poppoints.csv }{A .csv file containing the population support points and probabilities}
#' \item{poparam.csv }{A .csv file containing a summary of the population parameter values, including
#' mean, standard deviation, coefficient of variation, variance, and median}
#' \item{popcor.csv }{A .csv file containing the population parameter correlation matrix}
#' \item{popcov.csv }{A .csv file containing the population parameter covariance matrix}
#' \item{cycle.pdf }{A .pdf file containing the run cycle information (see \code{\link{plot.PMcycle}})}
#' \item{cycle.png }{A thumbnail of the run cycle information for the .html file}
#' \item{final.pdf }{A .pdf file containing the population final cycle information (see \code{\link{plot.PMfinal}})}
#' \item{final.png }{A thumbnail of the population final cycle information for the .html file}
#' \item{opx.pdf }{One or more .pdf files, where \emph{x} is the number of the output equation, each containing
#' two observed vs. predicted plots: population and individual Bayesian posterior predictions (see \code{\link{plot.PMop}})}
#' \item{opx.png }{One or more thumnails of the observed vs. predicted plots for the .html file}
#' \item{NPAGout.Rdata }{An R data file containing the output of \code{\link{NPparse}}, \code{\link{makeFinal}},
#' \code{\link{makeCycle}}, \code{\link{makeOP}}, \code{\link{makeCov}}, \code{\link{makePop}}, \code{\link{makePost}}, and 
#' the data file for the run read by \code{\link{PMreadMatrix}}.  
#' This file can be loaded using \code{\link{NPload}}.}
#' @author Michael Neely


NPreport <- function(wd,icen="median"){
  setwd(wd)
  if (file.exists("NP_RF0001.TXT")){
    NPdata <- suppressWarnings(tryCatch(NPparse(),error= function(e) {e <- NULL;cat("\nWARNING: The run did not complete successfully.\n")}))
    post <- suppressWarnings(tryCatch(makePost(NPdata,run=1),error = function(e) {e <- NULL;cat("\nWARNING: error in extraction of posterior Bayesian predictions at time ttpred; 'PMpost' object not saved.\n\n")}))
    pop <- suppressWarnings(tryCatch(makePop(NPdata),error = function(e) {e <- NULL;cat("\nWARNING: error in extraction of population predictions at time tpred; 'PMpop' object not saved.\n\n")}))
    
    cat("\n\n")
    flush.console()
    CSSfile <- paste(.libPaths(),"/Pmetrics/report/Pmetrics.css",sep="")
    
    if(length(grep("R2HTML",installed.packages()[,1]))==0){
      install.packages("R2HTML",repos="http://cran.cnr.Berkeley.edu",dependencies=T)
    }
    require(R2HTML)
    target <- HTMLInitFile(wd,"NPAGreport",CSSFile=CSSfile,Title="NPAG output")
    #header
    dtstamp <- format(Sys.time(),"%d %b %Y at %H:%M")
    HTML("<h4>Laboratory of Applied Pharmacokinetics&nbsp&nbsp&#8226&nbsp&nbsp 4650 Sunset Blvd. MS#51, Los Angeles, CA 90027&nbsp&nbsp&#8226&nbsp&nbsp(323) 361-5046
        &nbsp&nbsp&#8226&nbsp&nbsp<a href='http://www.lapk.org' target='_blank'>www.lapk.org</a><br>")
    HTML(paste("<h1>Report generated by Pmetrics package for R on",dtstamp,"</h1>"))
    if(length(NPdata)>0){
      HTML("<h2 id='Contents'>Table of Contents</h2>")
      HTMLli("<a href='#Summary'>Summary</a>")
      HTMLli("<a href='#Cycle'>Cycle information</a>")
      HTMLli("<a href='#Marginals'>Marginal population parameter distributions</a>")
      HTMLli("<a href='#Spoints'>Support points</a>")
      HTMLli("<a href='#Param'>Population parameter estimate summary statistics</a>")
      HTMLli("<a href='#Cov'>Covariance matrix for population parameter estimates</a>")
      HTMLli("<a href='#Cor'>Correlation matrix for population parameter estimates</a>")
      HTMLli("<a href='#OP'>Observed vs. predicted plots</a>")
      HTMLbr(x=3)
      
      #summary
      if(NPdata$nofix==0){parfix <- "There were no fixed parameters."
      } else {parfix <- paste("Fixed parameters:",paste(NPdata$parfix,collapse=", "))}
      ilog <- NPdata$ilog
      if(is.null(NPdata$converge)){
        same <- 0
        for (i in 2:length(ilog)){
          if ((ilog[i]-ilog[i-1]) < 1e-04) same <- same+1
        }
        if(same %% 11 == 0) {
          coninterp <- "(The run converged.)"
        } else {
          coninterp <- "(The run did not converge before the last cycle.)"
        }
      } else {
        coninterp <- switch(1+NPdata$converge,"(The run did not converge before the last cycle.)","(The run converged.)","","(<span style='color:red'>The run ended with a Hessian Error.</span>)")
      }
      if(!is.null(NPdata$prior)){
        extra <- paste("Prior density: ",c("Non-uniform (prior.txt)","Uniform")[1+as.numeric(NPdata$prior=="UNIFORM")],"<br>",
                       "Assay error model: ",switch(NPdata$ERRmod,"SD","SD, gamma","SD, lambda","gamma"),"<br>",sep="")
      } else extra <- NA
      HTML("<h2 id='Summary'>Summary
         &nbsp<a href='#Contents'><span>Back to Contents</span></a>
         &nbsp<a href='#Cycle'><span>Next Section</span></a></h2>")
      HTML(paste("Output file: <a href=",file.path(wd),"/NP_RF0001.TXT target=_blank>",file.path(wd),"/NP_RF0001.TXT</a><br>",
                 "Random parameters: ",paste(NPdata$par,collapse=", "),"<br>",
                 parfix,"<br>",
                 "Number of analyzed subjects: ",NPdata$nsub,"<br>",
                 "Number of output equations: ",NPdata$numeqt,"<br>",
                 "Number of cycles: ",NPdata$icyctot,"  ",coninterp,"<br>",
                 "Additional covariates: ",paste(NPdata$covnames,collapse=", "),"<br>",extra,sep=""))
      
      if (NPdata$negflag){ HTML("WARNING: There were negative pop/post predictions.")}
      HTMLbr(x=2)
      
      #icycle plot
      if(NPdata$icyctot > 0){
        cycle <- suppressWarnings(tryCatch(makeCycle(NPdata),error = function(e) {e <- NULL;cat("\nWARNING: error in extraction of cycle information; 'PMcycle' object not saved.\n\n")}))
        if(!all(is.null(cycle))){
          pdf(file="cycle.pdf",width=12,height=10); plot(cycle,cex.lab=1.4,font=2,cex.axis=1.2); dev.off()
          png(filename="cycle.png",width=1200,height=1000); plot(cycle,cex.lab=1.4,font=2,cex.axis=1.2); dev.off()
          HTML("<h2>Cycle information
            &nbsp<a id='Cycle' href='cycle.pdf'><span>Open file</span></a>
             &nbsp<a href='#Contents'><span>Back to Contents</span></a>
             &nbsp<a href='#Marginals'><span>Next Section</span></a></h2>")
          HTML("<img border='0' src='cycle.png' alt='Cycle Information' />")
        } else {
          HTML("<h2>Cycle information
            &nbsp<a id='Cycle'></a>
             &nbsp<a href='#Contents'><span>Back to Contents</span></a>
             &nbsp<a href='#Marginals'><span>Next Section</span></a></h2>")
          HTML("No cycles in this run.")
        }
      }
      #marginals
      final <- suppressWarnings(tryCatch(makeFinal(NPdata),error = function(e) {e <- NULL;cat("\nWARNING: error in extraction of final cycle parameter values; 'PMfinal' object not saved.\n\n")}))
      if(!all(is.null(final))){
        report.table <- data.frame(mean=final$popMean,sd=final$popSD,CV=final$popCV,var=final$popVar,
                                   median=final$popMedian)
        pdf(file="final.pdf",width=12,height=4*ceiling(NPdata$nvar/3)); plot(final,density=F,cex.lab=2.0,font=2,cex.axis=1.5); dev.off()
        png(filename="final.png",width=1200,height=400*ceiling(NPdata$nvar/3)); plot(final,density=F,cex.lab=2.0,font=2,cex.axis=1.5); dev.off()
        HTML("<h2>Marginal population parameter distributions
            &nbsp<a id='Marginals' href='final.pdf'><span>Open file</span></a>
           &nbsp<a href='#Contents'><span>Back to Contents</span></a>
           &nbsp<a href='#Spoints'><span>Next Section</span></a></h2>")
        HTML("<img border='0' src='final.png' alt='Marginal Densities' />")
        #Support point matrix
        HTML("<h2>Support points
            &nbsp<a id='Spoints' href='poppoints.csv'><span>Open file</span></a>
           &nbsp<a href='#Contents'><span>Back to Contents</span></a>
           &nbsp<a href='#Param'><span>Next Section</span></a></h2>")
        HTML(final$popPoints,align="left")
        #popparam
        HTML("<h2>Population parameter estimate summary statistics
            &nbsp<a id='Param' href='popparam.csv'><span>Open file</span></a>
           &nbsp<a href='#Contents'><span>Back to Contents</span></a>
           &nbsp<a href='#Cov'><span>Next Section</span></a></h2>")
        HTML(report.table,align="left")
        #covariance matrix
        HTML("<h2>Covariance matrix for population parameter estimates
            &nbsp<a id='Cov' href='popcov.csv'><span>Open file</span></a>
           &nbsp<a href='#Contents'><span>Back to Contents</span></a>
           &nbsp<a href='#Cor'><span>Next Section</span></a></h2>")
        HTML(final$popCov,align="left")
        #correlation matrix
        HTML("<h2>Correlation matrix for population parameter estimates
            &nbsp<a id='Cor' href='popcor.csv'><span>Open file</span></a>
           &nbsp<a href='#Contents'><span>Back to Contents</span></a>
           &nbsp<a href='#OP'><span>Next Section</span></a></h2>")
        HTML(final$popCor,align="left")
      }
      
      #OP
      HTML("<h2 id='OP'>Observed vs. predicted plots
            &nbsp<a href='#Contents'><span>Back to Contents</span></a></h2>")
      op <- suppressWarnings(tryCatch(makeOP(NPdata,icen=icen),error = function(e) {e <- NULL;cat("\nWARNING: error in extraction of observed vs. population predicted data; 'PMop' object not saved.\n\n")}))
      for (i in 2*(1:NPdata$numeqt)){
        if(!all(is.null(op))){  
          OPpng <-paste("op",i/2,".png",sep="")
          OPpdf <-paste("op",i/2,".pdf",sep="")
          HTML(paste("<h3>Output",i/2,"&nbsp<a href='",OPpdf,"'><span>Open file</span></a></h3>"))
          png(filename=OPpng,width=1200,height=600)
          par(mfrow=c(1,2))
          plot(op[[i-1]],ylab="Population Predicted",x.stat=0.4,cex.stat=1.2,font=2)
          plot(op[[i]],ylab="Individual Predicted",x.stat=0.4,cex.stat=1.2,font=2)
          par(mfrow=c(1,1))
          dev.off()
          pdf(file=OPpdf,width=12,height=6)
          par(mfrow=c(1,2))
          plot(op[[i-1]],ylab="Population Predicted",x.stat=0.4,cex.stat=1.0,font=2)
          plot(op[[i]],ylab="Individual Posterior Predicted",x.stat=0.4,cex.stat=1.0,font=2)
          par(mfrow=c(1,1))
          dev.off()
          HTML(paste("<img border='0' src='",OPpng,"' alt='OPplot' />",sep=""))
          
        }
      }
      
      HTMLEndFile()
      cov <- suppressWarnings(tryCatch(makeCov(NPdata),error = function(e) {e <- NULL;cat("\nWARNING: error in extraction of covariate-parameter data; 'PMcov' object not saved.\n\n")}))
      if(!all(is.null(final))){
        write.csv(report.table,"popparam.csv",row.names=T)
        write.csv(final$popPoints,"poppoints.csv",row.names=T)
        write.csv(final$popCov,"popcov.csv",row.names=T)
        write.csv(final$popCor,"popcor.csv",row.names=T)
      }
      if(NPdata$mdata != "NA") {mdata <- PMreadMatrix(paste("../inputs/",NPdata$mdata,sep=""),quiet=T)} else {mdata <- NA}
      
      cat(paste("\n\n\nSaving R data objects to ",wd,"......\n\n",sep=""))
      cat("\nUse NPload() to load them.\n")
      cat("\nThe following objects have been saved:\n")
      cat("\nNPdata: All output from NPAG\n")
      if(!all(is.null(pop))) cat("pop: Population predictions at regular, frequent intervals\n")
      if(!all(is.null(post))) cat("post: Posterior predictions at regular, frequent inteverals\n")
      if(!all(is.null(final))) cat("final: Final cycle parameters and summary statistics\n")
      if(!all(is.null(cycle))) cat("cycle: Cycle information\n")
      if(!all(is.null(op))) cat("op: Observed vs. population and posterior predicted\n")
      if(!all(is.null(cov))) cat("cov: Individual covariates and Bayesian posterior parameters\n")
      if(length(mdata)>1) cat("mdata: The data file used for the run\n")
      NPAGout <- list(NPdata=NPdata,pop=pop,post=post,final=final,cycle=cycle,op=op,cov=cov,mdata=mdata)
      save(NPAGout,file="NPAGout.Rdata")
      return(invisible(NULL))
    }
  }
  
  errfile <- list.files(pattern="^ERROR") #either NP_RF doesn't exist or isn't readable
  if(length(errfile)>0){
    errmessage <- readLines(errfile)
    errmessage <- paste(errmessage,collapse="")
    errmessage <- gsub("  "," ",errmessage)
    errmessage <- sub("^ *","",errmessage)
    
    HTML("<h2>ERROR REPORT<h2>")
    HTML(errmessage)
    HTMLEndFile()
    return(invisible(NULL))
  }
}

