#' \code{plot.PMfinal} plots \emph{PMfinal} objects
#'
#' If \code{formula} is specified, a different plot window will open with a 3-dimensional object.
#' In this window, the plot can be rotated in 3 dimensions by dragging it with the left mouse
#' button held down.  Selecting regions on the plot that contain points with the right mouse
#' button held down will annotate the points with the x and y values.  Right-clicking a region
#' without points will terminate the annotation process, but the plot window will remain open.
#' If \code{snap=T}, a snapshot will be saved to the working directory at this point.
#'
#' @title Plot Pmetrics Final Cycle Parameter Value Distributions
#' @method plot PMfinal
#' @param x The name of an \emph{PMfinal} data object generated by \code{\link{makeFinal}}
#' @param formula An optional formula of the form \code{y ~ x}, where \code{y} and \code{x}
#' are two model parameters to plot in a 3-dimensional bivariate plot.  See details.
#' @param pdf Boolean operator to send output to a pdf file; the default is \code{False}
#' @param cex.lab Size of the plot labels.
#' @param snap Boolean operator to save a snapshot of a 3-D bivariate plot to the working directory; the default is \code{False}.
#' This parameter is irrelevant for standard univariate marginal plots.
#' @param lwd Width of the histogram lines in the univariate marginal parameter distributions.
#' @param col This parameter will be applied to the histogram lines of a univariate marginal
#' plot, or the sphere color of a bivariate plot and is \dQuote{red} by default.
#' @param density Boolean operator to plot a kernel density function overlying the histogram
#' of a univarite marginal parameter distribution from NPAG; the default is \code{False}.
#' See \code{\link{density}}.  Ignored for IT2B output.
#' @param standard Standardize the normal parameter distribution plots from IT2B to the same
#' scale x-axis.  Ignored for NPAG output.
#' @param \dots Other parameters as found in \code{\link{plot.default}}.
#' @return Plots the object.
#' @author Michael Neely
#' @seealso \code{\link{makeFinal}}, \code{\link{plot}}, \code{\link{par}}, \code{\link{axis}}
#' @S3method plot PMfinal
#' @examples
#' data(PMex1)
#' final <- makeFinal(PMex1)
#' plot(final)
#' plot(final,col="blue",density=TRUE)
#' plot(final,Kel~Vol)



plot.PMfinal <- function(x,formula,pdf=F,cex.lab=1.2,snap=F,lwd=4,col="red",density=F,standard=T,...){

  if(missing(formula)){
    data <- x
    if(!pdf) {par(mfrow=c(ceiling(length(data$popMean)/3),ifelse(length(data$popMean)>2,3,length(data$popMean))))}
    if(inherits(data,"NPAG")){
      for (i in 1:(ncol(data$popPoints)-1)){
        plot(data$popPoints[,"prob"]~data$popPoints[,i],type="h",lwd=lwd,col=col,xlab=names(data$popPoints)[i],xlim=data$ab[i,],
            ,ylab="",cex.lab=cex.lab,...)
        abline(v=data$ab[i,],lty=2,lwd=1,col="black")
        if(density & nrow(data$popPoints)>1){
          den <- density(data$popPoints[,i])
          den$y <- den$y/(max(den$y)/max(data$popPoints[,"prob"]))
          lines(den)
        }
      } 
    }
    if(inherits(data,"IT2B")){
      for (i in 1:(length(data$popMean))){
        x <- seq(data$ab[i,1],data$ab[i,2],(data$ab[i,2]-data$ab[i,1])/1000)
        y <- dnorm(x,mean=data$popMean[i],sd=data$popSD[i])
        if (standard){xlim <- range(data$ab)} else {xlim <- data$ab[i,]}
        plot(x=x,y=y,type="l",lwd=lwd,col=col,xlab=names(data$popMean)[i],xlim=xlim,
            ,ylab="Probability",cex.lab=cex.lab,...)
        abline(v=data$ab[i,],lty=2,lwd=1,col="black")
        abline(v=data$popMean[i],lwd=1,col="black")
      } 
    }
    par(mfrow=c(1,1))
} else {
    if(inherits(data,"IT2B")) stop("Bivariate plots only available for NPAG output\n")
    data <- x
    keep <- NULL
    yCol <- as.character(attr(terms(formula),"variables")[2])
    xCol <- as.character(attr(terms(formula),"variables")[3])
    x <- model.frame(formula=formula,data=data$popPoints)[2][,1]
    y <- model.frame(formula=formula,data=data$popPoints)[1][,1]
    z <- data$popPoints[,"prob"]

    if(length(grep("rgl",installed.packages()[,1]))==0){
        install.packages("rgl",repos="http://cran.cnr.Berkeley.edu",dependencies=T)
    }
    require(rgl)
 

  xmin <- min(x)
  xmax <- max(x)
  ymin <- min(y)
  ymax <- max(y)
  zmin <- min(z)
  zmax <- max(z)
  open3d(mouseMode=c("trackball","none","zoom"),windowRect=c(0,0,1024,1024))
  plot3d(x,y,z,type="s",col=col,size=3,
         xlab=paste("x =",xCol),ylab=paste("y =",yCol),zlab="z = Prob",
         xlim=c(xmin-0.5*xmin,xmax+0.5*xmax),ylim=c(ymin-0.5*ymin,ymax+0.5*ymax),
         zlim=c(zmin-0.5*zmin,zmax+0.5*zmax))

  while(is.null(keep) | any(keep)){
  f<-select3d("right")
  keep <- f(x,y,z)
  texts3d(x=x[keep],y=y[keep],z=z[keep],
         text=paste(round(x[keep],2),round(y[keep],2),sep=", "),
         adj=c(0,-1.5),cex=0.7)
}
if(snap){snapshot3d(filename=paste("PMmarg3Dplot",format(Sys.time(),"-%m%d%-Y%H%M"),".png",sep=""))}
}
return(invisible(1))
}
