# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_Pmetrics_wrappers", use_symbols = TRUE, package_name = "Pmetrics")

#' @usage NULL
#' @useDynLib Pmetrics, .registration = TRUE
NULL

#' Simulates the first subject in the data set using the model DSL source.
#' @param data_path Path to the data file.
#' @param model_source DSL source code for the model.
#' @param spp One support point as a numeric vector with probabiltity.
#' @param kind Kind of model, which can either be "ODE" or "Analytical".
#' @param solver Optional ODE solver name.
#' @return Simulation results.
#' @keywords internal
#' @export
simulate_one <- function(data_path, model_source, spp, kind, solver = NULL) .Call(wrap__simulate_one, data_path, model_source, spp, kind, solver)

#' Simulates all subjects in the data set using the model DSL source.
#' @param data_path Path to the data file.
#' @param model_source DSL source code for the model.
#' @param theta Data frame of support points.
#' @param kind Kind of model, which can either be "ODE" or "Analytical".
#' @param solver Optional ODE solver name.
#' @return Simulation results.
#' @keywords internal
#' @export
simulate_all <- function(data_path, model_source, theta, kind, solver = NULL) .Call(wrap__simulate_all, data_path, model_source, theta, kind, solver)

#' Validates DSL model source against the runtime compiler.
#' @param model_source DSL source code for the model.
#' @param kind Kind of model, which can either be "ODE" or "Analytical".
#' @param solver Optional ODE solver name.
#' @return Result of the validation process.
#' @keywords internal
#' @export
validate_model_source <- function(model_source, kind, solver = NULL) .Call(wrap__validate_model_source, model_source, kind, solver)

#' Checks if Cargo is installed on the system.
#' @return TRUE if Cargo is installed, FALSE otherwise.
#' @keywords internal
#' @export
is_cargo_installed <- function() .Call(wrap__is_cargo_installed)

#' Fits the model DSL source to the data using the provided parameters.
#' @param model_source DSL source code for the model.
#' @param data Path to the data file.
#' @param params List of fitting parameters.
#' @param output_path Path to save the fitting results.
#' @param kind Kind of model, which can either be "ODE" or "Analytical".
#' @param solver Optional ODE solver name.
#' @return Result of the fitting process.
#' @keywords internal
#' @export
fit <- function(model_source, data, params, output_path, kind, solver = NULL) .Call(wrap__fit, model_source, data, params, output_path, kind, solver)

#' Retrieves the model parameters from compiled DSL metadata.
#' @param model_source DSL source code for the model.
#' @param kind Kind of model, which can either be "ODE" or "Analytical".
#' @return List of model parameters.
#' @keywords internal
#' @export
model_parameters <- function(model_source, kind) .Call(wrap__model_parameters, model_source, kind)

#' Initialize the tracing subscriber with the custom R formatter
#' @keywords internal
#' @export
setup_logs <- function() .Call(wrap__setup_logs)


# nolint end
