# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_Pmetrics_wrappers", use_symbols = TRUE, package_name = "Pmetrics")

#' @usage NULL
#' @useDynLib Pmetrics, .registration = TRUE
NULL

#' Simulates the first subject in the data set using the given model.
#' @param data_path Path to the data file.
#' @param model_source Model definition written in the pharmsol DSL.
#' @param spp One support point as a numeric vector.
#' @return Simulation results.
#' @keywords internal
#' @export
simulate_one <- function(data_path, model_source, spp) .Call(wrap__simulate_one, data_path, model_source, spp)

#' Simulates all subjects in the data set using the given model.
#' @param data_path Path to the data file.
#' @param model_source Model definition written in the pharmsol DSL.
#' @param theta Data frame of support points.
#' @return Simulation results.
#' @keywords internal
#' @export
simulate_all <- function(data_path, model_source, theta) .Call(wrap__simulate_all, data_path, model_source, theta)

#' Fits the given model to the data using the provided settings.
#' @param model_source Model definition written in the pharmsol DSL.
#' @param data Path to the data file.
#' @param params List of fitting parameters.
#' @param output_path Path to save the fitting results.
#' @return Result of the fitting process.
#' @keywords internal
#' @export
fit <- function(model_source, data, params, output_path) .Call(wrap__fit, model_source, data, params, output_path)

#' Retrieves the model parameters from the given model.
#' @param model_source Model definition written in the pharmsol DSL.
#' @return List of model parameters.
#' @keywords internal
#' @export
model_parameters <- function(model_source) .Call(wrap__model_parameters, model_source)

#' Initialize the tracing subscriber with the custom R formatter
#' @keywords internal
#' @export
setup_logs <- function() .Call(wrap__setup_logs)


# nolint end
