# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_Pmetrics_wrappers", use_symbols = TRUE, package_name = "Pmetrics")

#' @usage NULL
#' @useDynLib Pmetrics, .registration = TRUE
NULL

#' Return string `"Hello rust!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

#' Receives a path to a CSV file and returns true if the file exists.
#' @export
file_exists <- function(path) .Call(wrap__file_exists, path)

#'@export
simulate <- function(data_path, model_path, spp) .Call(wrap__simulate, data_path, model_path, spp)

#'@export
compile_model <- function(model_path, output_path, params) invisible(.Call(wrap__compile_model, model_path, output_path, params))


# nolint end
