#Print methods
#Use menu item Code -> Jump To... for rapid navigation


# MMopt -------------------------------------------------------------------

#' @title Print Pmetrics Multiple-Model Optimal Sampling Objects
#' @description
#' `r lifecycle::badge("stable")`
#'
#' Print *MMopt* objects
#'
#' @title Print Pmetrics Multiple-Model Optimal Sampling Objects
#' @method print MMopt
#' @param x The name of an *MMopt* data object generated by [MM_opt]
#' @param ... Not used
#' @return Prints the optimal sampling times and Bayes Risk.
#' @author Michael Neely
#' @seealso [MM_opt]
#' @export

print.MMopt <- function(x, ...) {
  cat("Multiple model optimal sample times\n")
  cat("-----------------------------------\n")
  for (i in 1:length(x$sampleTime)) {
    cat(paste("Sample ", i, ": ", x$sampleTime[i], "\n", sep = ""))
  }
  cat(paste("\nBayes Risk: ", x$bayesRisk, "\n", sep = ""))
}


# Summary PM_data -----------------------------------------------------------------

#' @title Summarize Pmetrics Data
#' @description
#' `r lifecycle::badge("stable")`
#'
#' @details
#' Print the summary of [PM_data] object.
#'
#' Summarize the raw data used for a Pmetrics run.
#'
#' @method print summary.PMmatrix
#' @param x An object made by [summary.PM_data].
#' @return A printed object
#' @author Michael Neely
#' @param ... Not used.
#' @seealso [summary.PM_data]
#' @examples
#' library(PmetricsData)
#' dataEx$summary()
#' @export

print.summary.PM_data <- function(x, ...) {
  #   order of objects
  #   nsub
  #   ndrug
  #   numeqt
  #   nobsXouteq
  #   missObsXouteq
  #   ncov
  #   ndoseXid
  #   nobsXid
  #   doseXid
  #   obsXid
  #   cov
  #   formula
  
  cat(paste("\nNumber of subjects:", x$nsub, "\n"))
  cat(paste("Number of inputs:", x$ndrug, "\n"))
  cat(paste("Number of outputs:", x$numeqt, "\n"))
  for (i in 1:x$numeqt) {
    cat(paste("Total number of observations (outeq ", i, "): ", x$nobsXouteq[i], ", with ", x$missObsXouteq[i], " (", sprintf("%.3f", 100 * x$missObsXouteq[i] / x$nobsXouteq[i]), "%) missing\n", sep = ""))
  }
  cat(paste("Number of covariates:", x$ncov, "\n"))
  cat(paste("\nTHE FOLLOWING ARE MEAN (SD), MIN TO MAX\n", paste(rep("-", 75), collapse = ""), "\n", sep = ""))
  cat("\nINPUTS\n")
  for (i in 1:x$ndrug) {
    if (x$ndrug == 1) {
      cat(paste("Number of doses per subject (input ", i, "): ", sprintf("%.3f", mean(x$ndoseXid, na.rm = T)), " (", sprintf("%.3f", sd(x$ndoseXid, na.rm = T)), "), ", sprintf("%.3f", min(x$ndoseXid, na.rm = T)), " to ", sprintf("%.3f", max(x$ndoseXid, na.rm = T)), "\n", sep = ""))
      cat(paste("Dose per subject (input ", i, "): ", sprintf("%.3f", mean(unlist(x$doseXid), na.rm = T)), " (", sprintf("%.3f", sd(unlist(x$doseXid), na.rm = T)), "), ", sprintf("%.3f", min(unlist(x$doseXid), na.rm = T)), " to ", sprintf("%.3f", max(unlist(x$doseXid), na.rm = T)), "\n", sep = ""))
    } else {
      cat(paste("Number of doses per subject (input ", i, "): ", sprintf("%.3f", mean(x$ndoseXid[, i], na.rm = T)), " (", sprintf("%.3f", sd(x$ndoseXid[, i], na.rm = T)), "), ", sprintf("%.3f", min(x$ndoseXid[, i], na.rm = T)), " to ", sprintf("%.3f", max(x$ndoseXid[, i], na.rm = T)), "\n", sep = ""))
      cat(paste("Dose (input ", i, "): ", sprintf("%.3f", mean(unlist(x$doseXid[, i]), na.rm = T)), " (", sprintf("%.3f", sd(unlist(x$doseXid[, i]), na.rm = T)), "), ", sprintf("%.3f", min(unlist(x$doseXid[, i]), na.rm = T)), " to ", sprintf("%.3f", max(unlist(x$doseXid[, i]), na.rm = T)), "\n", sep = ""))
    }
  }
  cat("\nOUTPUTS\n")
  for (i in 1:x$numeqt) {
    if (x$numeqt == 1) {
      nobs <- unlist(x$nobsXid)
      obs <- unlist(x$obsXid)
    } else {
      nobs <- unlist(x$nobsXid[, i])
      obs <- unlist(x$obsXid[, i])
    }
    obs <- obs[obs != -99]
    cat(paste("Number of obs per subject (outeq ", i, "): ", sprintf("%.3f", mean(nobs, na.rm = T)), " (", sprintf("%.3f", sd(nobs, na.rm = T)), "), ", sprintf("%.3f", min(nobs, na.rm = T)), " to ", sprintf("%.3f", max(nobs, na.rm = T)), "\n", sep = ""))
    cat(paste("Observation per subject (outeq ", i, "): ", sprintf("%.3f", mean(obs, na.rm = T)), " (", sprintf("%.3f", sd(obs, na.rm = T)), "), ", sprintf("%.3f", min(obs, na.rm = T)), " to ", sprintf("%.3f", max(obs, na.rm = T)), "\n", sep = ""))
  }
  if (x$ncov > 0) {
    cat("\nCOVARIATES\n")
    for (i in 1:x$ncov) {
      cat(paste(x$covnames[i], ": ", sprintf("%.3f", mean(unlist(x$cov[[i]]), na.rm = T)), " (", sprintf("%.3f", sd(unlist(x$cov[[i]]), na.rm = T)), "), ", sprintf("%.3f", min(unlist(x$cov[[i]]), na.rm = T)), " to ", sprintf("%.3f", max(unlist(x$cov[[i]]), na.rm = T)), "\n", sep = ""))
    }
  }
  
  if (!is.null(x$formula)) {
    cat(paste("\nFormula\n", paste(rep("-", 75), collapse = ""), "\n", sep = ""))
    print(x$formula)
  }
  cat(paste(paste(rep("-", 75), collapse = ""), "\nNote: See help(summary.PMmatrix) for accessing specific items by name.\n", sep = ""))
} # end function


# Summary PM_final ----------------------------------------------------------------


#' @title Print Summary of Parameter Values and Credibility Intervals
#' @description
#' `r lifecycle::badge("stable")`
#'
#' Print a Pmetrics Final Summary Object
#' @details
#' Print a summary of parameter medians and MAWD, with point estimates and credibilty intervals
#' from an object made by [summary.PM_final]. Users do not normally need to call this
#' function directly, as it will be the default method to display the object.
#'
#' @method print summary.PM_final
#' @param x A summary.PM_final object made by [summary.PM_final].
#' @param digits Integer, used for number of digits to print.
#' @param ... Not used.
#' @return A printed object.
#' @author Michael Neely
#' @seealso [summary.PM_final]
#' @examples
#' library(PmetricsData)
#' NPex$final$summary
#' @export

print.summary.PM_final <- function(x, digits = max(3, getOption("digits") - 3), ...) {
  x <- data.frame(x) # convert from tibble
  cat(paste("\nWeighted Medians (", 100 * (max(x$percentile) - min(x$percentile)),
    "% credibility interval)\n",
    sep = ""
  ))
  for (i in 1:(ncol(x) - 2)) {
    cat(paste(colnames(x[i]), ": ", round(x[2, i], digits), " (", round(x[1, i], digits), " - ", round(x[3, i], digits), ")\n", sep = ""))
  }

  cat(paste("\nMedian Absolute Weighed Differences (dispersion measure) (", 100 * (max(x$percentile) - min(x$percentile)),
    "% credibility interval)\n",
    sep = ""
  ))

  for (i in 1:(ncol(x) - 2)) {
    cat(paste(colnames(x[i]), ": ", round(x[5, i], digits), " (", round(x[4, i], digits), " - ", round(x[6, i], digits), ")\n", sep = ""))
  }
}


# Summary PM_op -------------------------------------------------------------------

#' @title Print Summary of Observations and Predictions
#' @description
#' `r lifecycle::badge("stable")`
#'
#' Print a Pmetrics Observed vs. Predicted Summary Object
#' 
#' @details
#' Print a summary of observations, predictions and errors in a summary.PMop object
#' made by [summary.PM_op]. Users do not normally need to call this
#' function directly, as it will be the default method to display the object.
#'
#' @title Print Summary of Observations and Predictions
#' @method print summary.PM_op
#' @param x An object made by [summary.PM_op].
#' @param digits Integer, used for number of digits to print.
#' @param ... Not used.
#' @return A printed object.
#' @author Michael Neely
#' @seealso [summary.PM_op]
#' @examples
#' library(PmetricsData)
#' NPex$op$summary
#' @export

print.summary.PM_op <- function(x, digits = max(3, getOption("digits") - 3), ...) {
  printSumWrk <- function(data, dataname) {
    cat(paste("\n", dataname, "\n", sep = ""))
    print(data$sumstat)
    cat(paste("\nPrediction type:", attr(x, "pred.type"), "\n"))
    cat("\n\n")
    cat(paste("Mean prediction error:", round(data$pe$mpe, digits), "\n"))
    cat(paste("Mean weighted prediction error (bias): ", round(data$pe$mwpe, digits), " (P=", round(data$wtd.t$p.value, digits), " different than 0)\n", sep = ""))
    cat(paste("Mean squared prediction error:", round(data$pe$mspe, digits), "\n"))
    cat(paste("Root mean squared error (RMSE):", round(data$pe$rmse, digits), "\n"))
    cat(paste("Percent root mean squared error (%RMSE):", round(data$pe$percent_rmse, digits), "\n"))
    cat(paste("Mean weighed squared prediction error:", round(data$pe$mwspe, digits), "\n"))
    cat(paste("Bias-adjusted mean squared prediction error:", round(data$pe$bamspe, digits), "\n"))
    cat(paste("Bias-adjusted mean weighted squared prediction error (imprecision):", round(data$pe$bamwspe, digits), "\n\n"))
  }
  # function to make summary
  if (inherits(x[[1]], "data.frame")) { # we just have one
    if (!is.na(x$pe[1])) {
      printSumWrk(x, "")
    } else {
      cat("NA\n")
    }
  } else {
    if (all(unlist(sapply(x, is.na)))) {
      cat("No observations.\n")
    } else {
      for (i in 1:length(x)) {
        if (!is.na(x[[i]][1])) {
          printSumWrk(x[[i]], paste("$", names(x)[i], sep = ""))
        } else {
          cat("NA\n")
        }
      }
    }
  }
}

