#' Plots \emph{MMopt} objects 
#'
#' Simulated observations are plotted on the y-axis vs. time on the x.axis.  
#' Optimal sampling times are indicated as vertical lines. Defaults for optimal
#' sample times are red, dash, width 2. Defaults for the `line` format are as
#' for [plot.PMsim].
#' 
#' @title Plot Pmetrics Multiple-Model Optimal Sampling Objects
#' @method plot MMopt
#' @param x The name of an \emph{MMopt} data object generated by \code{\link{MMopt}}
#' @param probs Default is NA. See [plot.PMsim] for details.
#' @template line
#' @param \dots Other parameters to pass to \code{\link{plot.PMsim}}.
#' @return Plots the simulation profiles with MMoptimal times indicated as vertical lines.
#' @author Michael Neely
#' @seealso \code{\link{plot.PMsim}}, \code{\link{plot}}, \code{\link{par}}, \code{\link{axis}}
#' @export


plot.MMopt <- function(x, probs = NA, line = T,...){
  
  line <- amendLine(line, default = list(color = "red", dash = "dash", width = 2))
  
  #parse dots
  arglist <- list(...)
  arglist$quiet = T
  arglist$probs = probs
  
  p <- do.call(plot.PMsim,c(list(x$simdata),arglist))$p
  
  p <- p %>% layout(shapes = lapply(x$sampleTime,
                                    function(t){
                                      vline(x = t, 
                                            color = line$color,
                                            dash = line$dash,
                                            width = line$width)
                                    })
  )
  print(p)
}
