#' Plot PM_valid objects
#'
#' Plot Pmetrics Validation Objects
#' 
#' Generates a plot of outputs (typically concentrations) on the y axis and time 
#' on the x axis. If `tad` was set to `TRUE`
#' when [make_valid] was called, then time may be either absolute (default) or time
#' after dose, controlled by the `tad` argument to this plot function.
#' The following items are included in the plot:
#' * Observed outputs. These may be either as measured for `type = "vpc"` or 
#' prediction corrected for `type = "pcvpc"`. Format of the observations is
#' controlled by the `marker` argument. The default is 
#' `list(color = "black", symbol = "circle-open", size = 8)`.
#' * Quantiles vs. time for observations. These are plotted by default as dashed
#' blue lines for the 2.5th and 97.5th percentiles and a solid red line for the 
#' median. Formatting and the value for each quantile can be controlled 
#' with the `upper`, `mid`, and `lower` arguments.
#' * 95% CI around the same quantiles of combined simulations from each subject.
#' The values and formatting for these quantile CIs are the same as for the observations, 
#' and also controlled with the `upper`, `mid`, and `lower` arguments.
#' 
#' Good vpc/pcvpc plots are considered to be those where the quantile lines for 
#' the oberservations lie within the 95%CI quantile regions for simulations, 
#' indicated that the model is "centered" on the data and faithfully captures the 
#' variability in the data. For an npde plot, one expects to see approximately 
#' normally distributed normalized prediction errors.
#' @method plot PMvalid
#' @param x The name of an \emph{PMvalid} data object generated by the [make_valid]
#' fundtion, which is usually called by the `$validate` method for [PM_result]
#' objects.
#' @param type Default is "vpc" for a visual predictive check, but could be 
#' "pcvpc" for a prediction-corrected visual predictive check, or
#' "npde" for a normalized prediction distribution error analysis/plot.
#' @template tad  
#' @template outeq 
#' @template log
#' @template marker
#' @param lower,mid,upper Controls characteristics of quantiles.
#' These arguments map to several plotly attributes.
#' Each can be a boolean value or a list.
#' `TRUE` will plot default characteristics. `FALSE` will suppress quantile plots.
#' The elements of the list for each argument are as follows:
#' * value The quantile value. Default for lower is 0.025, mid is 0.5, 
#' and upper is 0.975.
#' * color The color for both the 95%CI region around simulated quantile vs. time,
#' and the color of the line for the observation quantile vs. time.
#' Default for lower and upper is "dodgerblue" and for mid it is "red".
#' * dash The style of the obervation quantile line.  
#' See `plotly::schema()`, traces > scatter > attributes > line > dash > values.
#' Default for lower and upper is "dash" and for mid it is "solid".
#' * width Default is 1 for lower, mid, and upper.
#' * opacity The opacity of the 95%CI region around simulated quantile vs. time.
#' Default is 0.4 for lower, mid and upper, 
#' but can range between 0 (fully transparent) to 1 (fully opaque).
#' Example: `upper = list(value = 0.9, color = "red", dash = "longdash", opacity = 0.5, width = 2)`
#' @template grid
#' @template legend
#' @template xlim 
#' @template ylim 
#' @template xlab 
#' @template ylab 
#' @template dotsPlotly
#' @return Plots and returns the plotly object
#' @author Michael Neely
#' @seealso [makeValid]
#' @importFrom dplyr summarise
#' @importFrom nseval quo
#' @export
#' @family PMplots

plot.PMvalid <- function(x, 
                         type = "vpc", 
                         tad = F, 
                         outeq = 1,
                         log = F,
                         marker = T,
                         lower = T,
                         mid = T,
                         upper = T,
                         grid = T,
                         legend = F,
                         xlim, ylim,
                         xlab = c("Time", "Time after dose"), ylab = "Output",
                         ...){
  
  #to avoid modifying original object, x
  opDF <- x$opDF
  simdata <- x$simdata$obs
  
  
  if(outeq > max(opDF$outeq)){stop(paste("Your data do not contain",outeq,"output equations.\n"))}
  
  opDF <- opDF %>% filter(outeq == !!outeq) #filter to outeq
  simdata <- simdata %>% filter(outeq == !!outeq)  #filter to outeq
  
  dots <- list(...)
  
  marker <- amendMarker(marker, default = list(color = "black", symbol = "circle-open", size = 8))
  upper <- amendCI(upper, default = list(value = 0.975))
  mid <- amendCI(mid, default = list(value = 0.5, color = "red", dash = "solid"))
  lower <- amendCI(lower, default = list(value = 0.025))
  
  xaxis <- purrr::pluck(dots, "xaxis") #check for additional changes
  xaxis <- if(is.null(xaxis)) xaxis <- list()
  yaxis <- purrr::pluck(dots, "yaxis")
  yaxis <- if(is.null(yaxis)) yaxis <- list()
  
  if(!is.null(purrr::pluck(dots, "layout"))){stop("Specify individual layout elements, not layout.")}
  layout <- list()
  
  #legend
  legendList <- amendLegend(legend)
  layout <- modifyList(layout, list(showlegend = legendList$showlegend))
  if(length(legendList)>1){layout <- modifyList(layout, list(legend = within(legendList,rm(showlegend))))}
  
  #grid
  xaxis <- setGrid(xaxis, grid)
  yaxis <- setGrid(yaxis, grid)
  
  #axis labels if needed
  xtitle <- pluck(xaxis, "title")
  ytitle <- pluck(yaxis, "title")
  if(is.null(xtitle)){
    xaxis <- modifyList(xaxis, list(title = list(text =  xlab[1 + as.numeric(tad)])))
  }
  if(is.null(ytitle)){
    yaxis <- modifyList(yaxis, list(title = list(text = ylab)))
  }  
  
  #axis ranges
  if(!missing(xlim)){xaxis <- modifyList(xaxis, list(range = xlim)) }
  if(!missing(ylim)){yaxis <- modifyList(yaxis, list(range = ylim)) }
  
  #log y axis
  if(log){
    yaxis <- modifyList(yaxis, list(type = "log"))
  }
  
  #finalize layout
  layoutList <- modifyList(layout, list(xaxis = xaxis, yaxis = yaxis))
  
  #select correct time
  if(!tad){
    use.timeBinMedian <- sort(unique(opDF$timeBinMedian))
    use.optimes <- opDF$time
    use.opTimeBinMedian <- x$timeBinMedian$time
    use.opTimeBinNum <- x$timeBinMedian$bin
    use.simBinNum <- simdata$timeBinNum
  } else {
    if(!all(is.na(opDF$tadBinMedian))){
      cat("Warning: Using time after dose is misleading if not under steady-state conditions.\n")
      use.timeBinMedian <- sort(unique(opDF$tadBinMedian))
      use.optimes <- opDF$tad
      use.opTimeBinMedian <- x$tadBinMedian$time
      use.opTimeBinNum <- x$tadBinMedian$bin
      use.simBinNum <- simdata$tadBinNum
      if(xaxis$title=="Time") {xaxis$title <- "Time after dose"}
      
    } else {stop("Rerun makePMvalid and set tad argument to TRUE.\n")}
  }
  
  #calculate lower, 50th and upper percentiles for pcYij by time bins
  groupVar <- if(tad){quo(tadBinMedian)} else {quo(timeBinMedian)}
  quant_pcObs <- opDF %>%
    group_by(!!groupVar) %>%
    summarise(value = quantile(pcObs, probs = c(lower$value,mid$value,upper$value),na.rm = T),
              q = c(lower$value,mid$value,upper$value), .groups = "keep")
  names(quant_pcObs)[1] <- "time"
  
  #calculate lower, 50th and upper percentiles for Yij by time bin
  quant_Obs <- opDF %>%
    group_by(!!groupVar) %>%
    summarise(value = quantile(obs, probs = c(lower$value,mid$value,upper$value),na.rm = T),
              q = c(lower$value,mid$value,upper$value), .groups = "keep")
  names(quant_Obs)[1] <- "time"
  
  #calculate median and CI for upper, median, and lower for each bin
  simGroupVar <- if(tad){quo(tadBinNum)} else {quo(timeBinNum)}
  simCI <- simdata %>% group_by(simnum, !!simGroupVar) %>% summarise(value = quantile(out, probs = c(lower$value,mid$value,upper$value),na.rm = T),
                                                                     q = c("lower","mid","upper"), .groups = "keep") %>%
    group_by(bin = !!simGroupVar, q) %>% summarise(value = quantile(value, probs = c(lower$value,upper$value),na.rm = T),
                                                   ci = c(lower$value,upper$value), .groups = "keep") %>%
    pivot_wider(names_from = ci, values_from = value, names_prefix = "q")
  
  #combine obs and simCI
  quant_pcObs <- quant_pcObs %>% select(-q) %>% bind_cols(simCI)
  quant_Obs <- quant_Obs %>% select(-q) %>% bind_cols(simCI)
  
  
  
  #type specific options
  if(type=="vpc"){ 
    timeVar <- if(tad){quo(tad)} else {quo(time)}
    plotData <- list(obsQuant = quant_Obs,
                                    obs = opDF %>% 
                                      select(id, time = !!timeVar, obs))
                                   
  }
  if(type=="pcvpc"){ 
    timeVar <- if(tad){quo(tadBinMedian)} else {quo(timeBinMedian)}
    plotData <- list(obsQuant = quant_pcObs,
                                      obs = opDF %>% 
                                        select(id, time = !!timeVar, obs))
  }
  if(type=="vpc" | type=="pcvpc"){
    
    #GENERATE THE PLOT
    p <-  plotData$obsQuant %>% group_by(q) %>%
      plotly::plot_ly(x = ~time, y = ~value, 
                      colors = c(upper$color, mid$color, lower$color), 
                      linetypes = c(upper$dash, mid$dash, lower$dash),
                      color = ~q,
                      linetype = ~q) %>%
      #add simulation quantile CIs
      plotly::add_ribbons(ymin = ~q0.025, ymax = ~q0.975,
                          opacity = upper$opacity,
                          line = list(width = 0),
                          hoverinfo = "none") %>%
      #add observation quantiles
      plotly::add_lines(hovertemplate = "Time: %{x}<br>Out: %{y}<br><extra></extra>") %>%
      #add observations
      plotly::add_markers(data = plotData$obs,
                          x = ~time, y = ~obs, marker = marker, 
                          hovertemplate = "Time: %{x}<br>Out: %{y}<br>ID: %{text}<extra></extra>",
                          text = ~id,
                          inherit = F) %>%
      #add layout
      
      plotly::layout(xaxis = layoutList$xaxis,
                     yaxis = layoutList$yaxis,
                     showlegend = layoutList$showlegend,
                     legend = layoutList$legend) 
    
    #SEND TO CONSOLE
    print(p)
  }
  
  if(type=="npde"){
    if(!tad){
      if(is.null(x$npde)) stop("No npde object found.  Re-run makeValid.\n")
      if(inherits(x$npde[[outeq]], "NpdeObject")){
        plot(x$npde[[outeq]])
        par(mfrow=c(1,1))
      } else {
        cat(paste0("Unable to calculate NPDE for outeq ",outeq))
      }
    } else {
      if(is.null(x$npde_tad)) stop("No npde_tad object found.  Re-run makeValid with tad = T.\n")
      if(inherits(x$npde_tad[[outeq]], "NpdeObject")){
        plot(x$npde_tad[[outeq]])
        par(mfrow=c(1,1))
      } else {
        cat(paste0("Unable to calculate NPDE with TAD for outeq ",outeq))
      }
    }
    
    p <- NULL
  }
  return(p)
}
