#' Plots \emph{MMopt} objects 
#'
#' Simulated observations are plotted on the y-axis vs. time on the x.axis.  
#' Optimal sampling times are indicated as vertical lines. Defaults for optimal
#' sample times are red, dash, width 2. Defaults for the `line` format are as
#' for [plot.PMsim].
#' 
#' @title Plot Pmetrics Multiple-Model Optimal Sampling Objects
#' @method plot MMopt
#' @param x The name of an \emph{MMopt} data object generated by \code{\link{MMopt}}
#' @param probs Default is NA. See [plot.PMsim] for details.
#' @param line Passed to [plot.PM_sim] with default as `list(probs = NA)`.
#' @param times Format the vertical lines for optimal times. Default is
#' dashed red line. r template("line")` 
#' @param \dots Other parameters to pass to [plot.PM_sim].
#' @return Plots the simulation profiles with MMoptimal times indicated as vertical lines.
#' @author Michael Neely
#' @seealso [plot.PM_sim]
#' @export
#' @family PMplots


plot.MMopt <- function(x, line = list(probs = NA), times = T,...){
  
  times <- amendLine(times, default = list(color = "red", dash = "dash", width = 2))
  
  #parse dots
  arglist <- list(...)
  arglist$quiet = T
  arglist$line = line
  
  p <- do.call(plot.PM_sim,c(list(x$simdata),arglist))$p
  
  p <- p %>% layout(shapes = lapply(x$sampleTime,
                                    function(t){
                                      ab_line(v = t, line = times)
                                    })
  )
  print(p)
}
