#' @title Plot Pmetrics Multiple-Model Optimal Sampling Objects
#' @description
#' `r lifecycle::badge("stable")`
#'
#' Plots *MMopt* objects
#' @details
#' Simulated observations are plotted on the y-axis vs. time on the x.axis.
#' Optimal sampling times are indicated as vertical lines. Defaults for optimal
#' sample times are red, dash, width 2. Defaults for the `line` format are as
#' for [plot.PM_sim].
#'
#' @method plot MMopt
#' @param x The name of an *MMopt* data object generated by [MM_opt]
#' @param probs Default is NA. See [plot.PM_sim] for details.
#' @param line Passed to [plot.PM_sim] with default as `list(probs = NA)`.
#' @param times Format the vertical lines for optimal times. Default is
#' dashed red line. r template("line")`
#' @param ... Other parameters to pass to [plot.PM_sim].
#' @return Plots the simulation profiles with MMoptimal times indicated as vertical lines.
#' @author Michael Neely
#' @seealso [plot.PM_sim]
#' @export
#' @family PMplots


plot.MMopt <- function(x, line = list(probs = NA), times = T, ...) {
  mm_format <- amendLine(times, default = list(color = "red", dash = "dash", width = 2))

  # parse dots
  arglist <- list(...)
  arglist$quiet <- T
  arglist$line <- line

  p <- do.call(plot.PM_sim, c(list(x$simdata), arglist))$p


  if (!is.null(x$mmInt)) { # add MM interval times
    shapeList <- lapply(x$mmInt, function(m) {
      list(
        type = "rect",
        x0 = m[1],
        y0 = 0,
        x1 = m[2],
        y1 = 1,
        xref = "x",
        yref = "paper",
        fillcolor = "grey",
        opacity = 0.1,
        line = list(width = 0)
      )
    })
  } else {
    shapeList <- list()
  }

  shapeList <- append(shapeList, lapply(
    x$sampleTime,
    function(t) {
      ab_line(v = t, line = mm_format)
    }
  ))

  p <- p %>% layout(shapes = shapeList)

  print(p)
}
