#' @title Print Pmetrics Multiple-Model Optimal Sampling Objects
#' @description
#' `r lifecycle::badge("stable")`
#' 
#' Print *MMopt* objects 
#' 
#' @title Print Pmetrics Multiple-Model Optimal Sampling Objects
#' @method print MMopt
#' @param x The name of an *MMopt* data object generated by [MM_opt]
#' @param ... Not used
#' @return Prints the optimal sampling times and Bayes Risk.
#' @author Michael Neely
#' @seealso [MM_opt]
#' @export

print.MMopt <- function(x,...){

  cat("Multiple model optimal sample times\n")
  cat("-----------------------------------\n")
  for(i in 1:length(x$sampleTime)){
    cat(paste("Sample ",i,": ",x$sampleTime[i],"\n",sep=""))
  }
  cat(paste("\nBayes Risk: ",x$bayesRisk,"\n",sep=""))
  
}
